config:
  env:
  issues:
    cppcheck:
      pattern: 'result/cppcheck.*.xml'
    cmake:
      pattern: 'result/make.*'
    gcc:
      pattern: 'result/make.*'
    junit:
      pattern: 'result/test-*.xml'
  archiveArtifacts:
    artifacts: 'result/*'


stages:
  - cppcheck
  - x86_build

stage:
  cppcheck:
    node: docker
    docker:
      image: sharaku/cppcheck
    script:
     - sh: cd build/linux-builds && sh 01-static_check.sh
    result: 'result/*'

  x86_build:
    node: docker
    docker:
      image: sharaku/cross-build
    script:
     - sh: cd build/linux-builds && sh 02-build.sh
    result: 'result/*'
